# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(820, 600)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 0, 731, 541))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_loading = QtWidgets.QWidget()
        self.tab_loading.setObjectName("tab_loading")
        self.pushButton_loading = QtWidgets.QPushButton(self.tab_loading)
        self.pushButton_loading.setGeometry(QtCore.QRect(260, 10, 191, 41))
        self.pushButton_loading.setObjectName("pushButton_loading")
        self.textEdit_output = QtWidgets.QTextEdit(self.tab_loading)
        self.textEdit_output.setGeometry(QtCore.QRect(70, 110, 591, 391))
        self.textEdit_output.setObjectName("textEdit_output")
        self.progressBar = QtWidgets.QProgressBar(self.tab_loading)
        self.progressBar.setGeometry(QtCore.QRect(160, 70, 411, 21))
        self.progressBar.setMinimumSize(QtCore.QSize(0, 0))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.tabWidget.addTab(self.tab_loading, "")
        self.tab_eda = QtWidgets.QWidget()
        self.tab_eda.setObjectName("tab_eda")
        self.pushButton_EDA = QtWidgets.QPushButton(self.tab_eda)
        self.pushButton_EDA.setGeometry(QtCore.QRect(240, 80, 201, 32))
        self.pushButton_EDA.setObjectName("pushButton_EDA")
        self.MplWidget = MplWidget(self.tab_eda)
        self.MplWidget.setGeometry(QtCore.QRect(60, 140, 611, 361))
        self.MplWidget.setMinimumSize(QtCore.QSize(400, 300))
        self.MplWidget.setObjectName("MplWidget")
        self.comboBox_eda = QtWidgets.QComboBox(self.tab_eda)
        self.comboBox_eda.setGeometry(QtCore.QRect(120, 30, 161, 32))
        self.comboBox_eda.setObjectName("comboBox_eda")
        self.comboBox_eda.addItem("")
        self.comboBox_eda_2 = QtWidgets.QComboBox(self.tab_eda)
        self.comboBox_eda_2.setGeometry(QtCore.QRect(310, 30, 161, 30))
        self.comboBox_eda_2.setObjectName("comboBox_eda_2")
        self.comboBox_eda_2.addItem("")
        self.comboBox_eda_2.addItem("")
        self.label = QtWidgets.QLabel(self.tab_eda)
        self.label.setGeometry(QtCore.QRect(140, 10, 111, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_eda)
        self.label_2.setGeometry(QtCore.QRect(340, 10, 111, 20))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.tab_eda)
        self.label_4.setGeometry(QtCore.QRect(520, 10, 111, 20))
        self.label_4.setObjectName("label_4")
        self.comboBox_eda_3 = QtWidgets.QComboBox(self.tab_eda)
        self.comboBox_eda_3.setGeometry(QtCore.QRect(500, 30, 161, 30))
        self.comboBox_eda_3.setObjectName("comboBox_eda_3")
        self.comboBox_eda_3.addItem("")
        self.tabWidget.addTab(self.tab_eda, "")
        self.tab_features = QtWidgets.QWidget()
        self.tab_features.setObjectName("tab_features")
        self.pushButton_feature = QtWidgets.QPushButton(self.tab_features)
        self.pushButton_feature.setGeometry(QtCore.QRect(260, 460, 191, 41))
        self.pushButton_feature.setObjectName("pushButton_feature")
        self.MplWidget_2 = MplWidget(self.tab_features)
        self.MplWidget_2.setGeometry(QtCore.QRect(60, 70, 611, 361))
        self.MplWidget_2.setMinimumSize(QtCore.QSize(611, 300))
        self.MplWidget_2.setObjectName("MplWidget_2")
        self.tabWidget.addTab(self.tab_features, "")
        self.tab_modeling = QtWidgets.QWidget()
        self.tab_modeling.setObjectName("tab_modeling")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_modeling)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 440, 141, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_7 = QtWidgets.QLabel(self.tab_modeling)
        self.label_7.setGeometry(QtCore.QRect(440, 30, 181, 21))
        self.label_7.setObjectName("label_7")
        self.label_3 = QtWidgets.QLabel(self.tab_modeling)
        self.label_3.setGeometry(QtCore.QRect(150, 360, 111, 21))
        self.label_3.setObjectName("label_3")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.tab_modeling)
        self.graphicsView_2.setGeometry(QtCore.QRect(20, 60, 341, 281))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_modeling)
        self.comboBox_3.setGeometry(QtCore.QRect(140, 380, 131, 31))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_modeling)
        self.comboBox_2.setGeometry(QtCore.QRect(470, 380, 131, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_5 = QtWidgets.QLabel(self.tab_modeling)
        self.label_5.setGeometry(QtCore.QRect(480, 360, 181, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_modeling)
        self.label_6.setGeometry(QtCore.QRect(80, 30, 181, 21))
        self.label_6.setObjectName("label_6")
        self.textEdit = QtWidgets.QTextEdit(self.tab_modeling)
        self.textEdit.setGeometry(QtCore.QRect(380, 60, 331, 281))
        self.textEdit.setObjectName("textEdit")
        self.tabWidget.addTab(self.tab_modeling, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(70, 40, 181, 21))
        self.label_8.setObjectName("label_8")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_2.setGeometry(QtCore.QRect(350, 70, 341, 281))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(280, 380, 111, 21))
        self.label_10.setObjectName("label_10")
        self.comboBox_4 = QtWidgets.QComboBox(self.tab)
        self.comboBox_4.setGeometry(QtCore.QRect(270, 410, 131, 31))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(270, 450, 141, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(380, 40, 181, 21))
        self.label_9.setObjectName("label_9")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView_3.setGeometry(QtCore.QRect(10, 70, 331, 281))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.tabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 820, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionExit_2 = QtWidgets.QAction(MainWindow)
        self.actionExit_2.setObjectName("actionExit_2")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit_2)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Traffic Accident in USA  Predictor"))
        self.pushButton_loading.setText(_translate("MainWindow", "Loading Data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_loading), _translate("MainWindow", "Loading"))
        self.pushButton_EDA.setText(_translate("MainWindow", "Plot"))
        self.comboBox_eda.setItemText(0, _translate("MainWindow", "Temperature"))
        self.comboBox_eda_2.setItemText(0, _translate("MainWindow", "Severity"))
        self.comboBox_eda_2.setItemText(1, _translate("MainWindow", "Waether Condtion"))
        self.label.setText(_translate("MainWindow", "Weather Condtion"))
        self.label_2.setText(_translate("MainWindow", "Road Condtion"))
        self.label_4.setText(_translate("MainWindow", "Severity"))
        self.comboBox_eda_3.setItemText(0, _translate("MainWindow", "Severity"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_eda), _translate("MainWindow", "EDA"))
        self.pushButton_feature.setText(_translate("MainWindow", "Run Random Forest"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_features), _translate("MainWindow", "Feature Selection"))
        self.pushButton_2.setText(_translate("MainWindow", "Run Model"))
        self.label_7.setText(_translate("MainWindow", "Classification Report"))
        self.label_3.setText(_translate("MainWindow", "Sample Weight"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "None"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Upsampled"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Downsampled"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "All features"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Top 10 features"))
        self.label_5.setText(_translate("MainWindow", "Feature Selection"))
        self.label_6.setText(_translate("MainWindow", "Confustion Matrix"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_modeling), _translate("MainWindow", "RF - Bagging"))
        self.label_8.setText(_translate("MainWindow", "Confustion Matrix"))
        self.label_10.setText(_translate("MainWindow", "Feature Selection"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "All features"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Top 10 features"))
        self.pushButton_3.setText(_translate("MainWindow", "Run Model"))
        self.label_9.setText(_translate("MainWindow", "Classification Report"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Adaptive Boosting Trees"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit_2.setText(_translate("MainWindow", "Exit"))

from mplwidget import MplWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

